// Single source of truth for the ATS studio registry.
// Shared by the job board (pages/index.js) and the alert cron (pages/api/cron).
// Format: "Studio Name": { platform, slug }
export const ATS_STUDIOS = {
  // ─── Ashby ───
  "Applied Intuition":        { platform:"ashby", slug:"applied" },
  "Arena":                    { platform:"ashby", slug:"arenanet" },
  "Atomic Theory":            { platform:"ashby", slug:"rocketsciencegg" },
  "Bad Robot Games":          { platform:"ashby", slug:"badrobotgames" },
  "Battle Creek Games":       { platform:"ashby", slug:"battle-creek-games" },
  "Believer Entertainment":   { platform:"ashby", slug:"believer" },
  "Bullet Farm":              { platform:"ashby", slug:"bulletfarm" },
  "Certain Affinity":         { platform:"ashby", slug:"certainaffinityinc" },
  "Gardens Interactive":      { platform:"ashby", slug:"gardens" },
  "Level":                    { platform:"ashby", slug:"level" },
  "Playgig":                  { platform:"ashby", slug:"playgig" },
  "Second Dinner":            { platform:"ashby", slug:"seconddinner" },
  "Series Entertainment":     { platform:"ashby", slug:"seriesai" },
  "Supercell":                { platform:"ashby", slug:"supercell" },
  "Super Evil MegaCorp":      { platform:"ashby", slug:"superevilmegacorp" },
  "TapBlaze":                 { platform:"ashby", slug:"tapblaze" },
  "Terminal Velocity":        { platform:"ashby", slug:"rocketsciencegg" },
  "thatgamecompany":          { platform:"ashby", slug:"thatgamecompany" },
  "Voodoo":                   { platform:"ashby", slug:"voodoo" },
  "Weekend":                  { platform:"ashby", slug:"weekend" },
  "Wolfjaw Studios":          { platform:"ashby", slug:"wolfjaw-careers" },
  // ─── ApplytoJob ───
  "Arcanaut Studios":         { platform:"applytojob", slug:"acrcanautstudios" },
  "Big Blue Bubble":          { platform:"applytojob", slug:"bigbluebubble" },
  "Certain Affinity":         { platform:"applytojob", slug:"certainaffinityinc" },
  "Hi-Rez Studios":           { platform:"applytojob", slug:"hirezstudios" },
  "Hololabs":                 { platform:"applytojob", slug:"hololabs" },
  "Iron Galaxy Studios":      { platform:"applytojob", slug:"irongalaxy" },
  "Lost Boys Interactive":    { platform:"applytojob", slug:"lostboysinteractive" },
  "Next Level Games":         { platform:"applytojob", slug:"nextlevelgames" },
  "Obsidian Entertainment":   { platform:"applytojob", slug:"obsidian" },
  "Shapeshifter Games":       { platform:"applytojob", slug:"shapeshiftergames" },
  "Sinn Studio":              { platform:"applytojob", slug:"sinnstudio" },
  "Templar Media":            { platform:"applytojob", slug:"templar" },
  "Titan Forge":              { platform:"applytojob", slug:"hirezstudios" },
  // ─── BambooHR ───
  "Avore":                    { platform:"bamboohr", slug:"avore" },
  "Budge Studios":            { platform:"bamboohr", slug:"budge" },
  "Cat Face":                 { platform:"bamboohr", slug:"catface" },
  "CerebralFix":              { platform:"bamboohr", slug:"cerebralfix" },
  "Clockwork Labs":           { platform:"bamboohr", slug:"clockworklabs" },
  "Compulsion Games":         { platform:"bamboohr", slug:"compulsiongames" },
  "Devolver Digital":         { platform:"bamboohr", slug:"devolverdigital" },
  "E-Line Media":             { platform:"bamboohr", slug:"elinemedia" },
  "Emberlab":                 { platform:"bamboohr", slug:"emberlab" },
  "Final Strike Games":       { platform:"bamboohr", slug:"finalstrikegames" },
  "Gasket Games":             { platform:"bamboohr", slug:"gasketgames" },
  "High 5 Games":             { platform:"bamboohr", slug:"high5games" },
  "Hyper Hippo Games":        { platform:"bamboohr", slug:"hyperhippoproductions" },
  "InXile Entertainment":     { platform:"bamboohr", slug:"inxile" },
  "King Show Games":          { platform:"bamboohr", slug:"kingshowgames" },
  "LBC Studios":              { platform:"bamboohr", slug:"lbcstudiosca" },
  "Lucid Dream":              { platform:"bamboohr", slug:"luciddreamvr" },
  "Ludia":                    { platform:"bamboohr", slug:"ludia" },
  "Moonshot Games":           { platform:"bamboohr", slug:"dreamhaven" },
  "Motorsport Games":         { platform:"bamboohr", slug:"motorsportgames" },
  "Offworld":                 { platform:"bamboohr", slug:"owi" },
  "Race Rocks":               { platform:"bamboohr", slug:"racerocks" },
  "Red Barrels":              { platform:"bamboohr", slug:"redbarrels" },
  "Relic":                    { platform:"bamboohr", slug:"relicentertainment" },
  "Schell Games":             { platform:"bamboohr", slug:"sg" },
  "Secret Door":              { platform:"bamboohr", slug:"dreamhaven" },
  "Seismic Squirrel":         { platform:"bamboohr", slug:"seismicsquirrel" },
  "Stardock":                 { platform:"bamboohr", slug:"stardock" },
  "Studio Wildcard":          { platform:"bamboohr", slug:"studiowildcard" },
  "Torn Banner Studios":      { platform:"bamboohr", slug:"tornbanner" },
  "Trio Tech":                { platform:"bamboohr", slug:"triotech" },
  "Turn Me Up Games":         { platform:"bamboohr", slug:"turnmeup" },
  "Uken Games":               { platform:"bamboohr", slug:"uken" },
  // ─── BreezyHR ───
  "AGBO":                     { platform:"breezy", slug:"agbo" },
  "Com2Us":                   { platform:"breezy", slug:"com2us" },
  "Flowplay":                 { platform:"breezy", slug:"flowplay-llc" },
  "Gamebreaking Studios":     { platform:"breezy", slug:"gamebreaking" },
  "Illfonic":                 { platform:"breezy", slug:"illfonic" },
  "Lucky Logic":              { platform:"breezy", slug:"lucky-logic" },
  "Magic Fuel Games":         { platform:"breezy", slug:"playstack" },
  "Puzzle Cats":              { platform:"breezy", slug:"puzzy-cats" },
  "Raid Base":                { platform:"breezy", slug:"raid-base-inc" },
  "Turbulent":                { platform:"breezy", slug:"turbulent" },
  // ─── Greenhouse studios ───
  "2k Games":                 { platform:"greenhouse", slug:"2k" },
  "2k Sports Lab":            { platform:"greenhouse", slug:"2k" },
  "31st Union":               { platform:"greenhouse", slug:"31stunion" },
  "A Thinking Ape":           { platform:"greenhouse", slug:"athinkingape" },
  "Absurd Ventures":          { platform:"greenhouse", slug:"absurdventures" },
  "App Lovin":                { platform:"greenhouse", slug:"applovin" },
  "Aspyr":                    { platform:"greenhouse", slug:"aspyrmediainc" },
  "Azra Games":               { platform:"greenhouse", slug:"azragames" },
  "Bandai Namco":             { platform:"greenhouse", slug:"bandainamco" },
  "Bend Studio":              { platform:"greenhouse", slug:"sonyinteractiveentertainmentglobal" },
  "Bit Reactor":              { platform:"greenhouse", slug:"bitreactor" },
  "Bonfire Studios":          { platform:"greenhouse", slug:"bonfirestudiosinc" },
  "Bungie":                   { platform:"greenhouse", slug:"bungie" },
  "Cat Daddy Games":          { platform:"greenhouse", slug:"catdaddy" },
  "Clipwire Games":           { platform:"greenhouse", slug:"tripledotstudios" },
  "Cloud Chamber":            { platform:"greenhouse", slug:"cloudchamberen" },
  "Crystal Dynamics":         { platform:"greenhouse", slug:"crystaldynamics" },
  "Daybreak Games":           { platform:"greenhouse", slug:"daybreakgames" },
  "Digital Extremes":         { platform:"greenhouse", slug:"digitalextremes" },
  "Discord":                  { platform:"greenhouse", slug:"discord" },
  "Eleventh Hour Games":      { platform:"greenhouse", slug:"eleventhhourgames" },
  "Epic Games":               { platform:"greenhouse", slug:"epicgames" },
  "Fanatics":                 { platform:"greenhouse", slug:"fanaticscollectibles" },
  "Firaxis":                  { platform:"greenhouse", slug:"firaxis" },
  "Fortis Games":             { platform:"greenhouse", slug:"fortisgames" },
  "Gearbox":                  { platform:"greenhouse", slug:"gearbox" },
  "Ghost Story Games":        { platform:"greenhouse", slug:"gsgcareers" },
  "Golden Ventures":          { platform:"greenhouse", slug:"faire" },
  "Halfbrick Studios":        { platform:"greenhouse", slug:"halfbrickstudios" },
  "Hasbro":                   { platform:"greenhouse", slug:"hasbro" },
  "Haven Studios":            { platform:"greenhouse", slug:"havenenglish" },
  "HB Studios":               { platform:"greenhouse", slug:"hbstudios" },
  "Highdive Games":           { platform:"greenhouse", slug:"highdive" },
  "Imagendary Studios":       { platform:"greenhouse", slug:"imagwndarystudios" },
  "Insomniac Games":          { platform:"greenhouse", slug:"insomniac" },
  "Kano":                     { platform:"greenhouse", slug:"kano" },
  "Krafton":                  { platform:"greenhouse", slug:"studiokraftonboard" },
  "Linden Lab":               { platform:"greenhouse", slug:"lindenlab" },
  "Lion Studios":             { platform:"greenhouse", slug:"tripledotstudios" },
  "Midsummer Studios":        { platform:"greenhouse", slug:"midsummerstudios" },
  "Mob Entertainment":        { platform:"greenhouse", slug:"mobentertainment" },
  "Mobilityware":             { platform:"greenhouse", slug:"mobilityware" },
  "Monomi Park":              { platform:"greenhouse", slug:"monomipark" },
  "MrBeast":                  { platform:"greenhouse", slug:"mrbeastyoutube" },
  "Natural Motion":           { platform:"greenhouse", slug:"nmcareers" },
  "Naughty Dog":              { platform:"greenhouse", slug:"naughtydog" },
  "NetEase Games":            { platform:"greenhouse", slug:"neteasegames" },
  "Never Forget Games":       { platform:"greenhouse", slug:"neverforgetgames" },
  "Nightdive Studios":        { platform:"greenhouse", slug:"nightdivestudios" },
  "Panic Button Games":       { platform:"greenhouse", slug:"panicbutton" },
  "Peoplefun":                { platform:"greenhouse", slug:"tripledotstudios" },
  "PlayQ":                    { platform:"greenhouse", slug:"playq" },
  "Psyonix":                  { platform:"greenhouse", slug:"epicgames" },
  "Retro Studios":            { platform:"greenhouse", slug:"nintendo" },
  "Riot Games":               { platform:"greenhouse", slug:"riotgames" },
  "Roblox":                   { platform:"greenhouse", slug:"roblox" },
  "Rockstar Games":           { platform:"greenhouse", slug:"rockstargames" },
  "Scopely":                  { platform:"greenhouse", slug:"scopely" },
  "Singularity 6":            { platform:"greenhouse", slug:"singularity6" },
  "Sony Studio":              { platform:"greenhouse", slug:"sonyinteractiveentertainmentglobal" },
  "Supernatural Studios":     { platform:"greenhouse", slug:"supernaturalstudios" },
  "Take-Two Interactive":     { platform:"greenhouse", slug:"taketwo" },
  "That's No Moon":           { platform:"greenhouse", slug:"thatsnomoonentertainment" },
  "The Pokemon Company":      { platform:"greenhouse", slug:"pokemoncareers" },
  "team LFG":                 { platform:"greenhouse", slug:"teamlfg" },
  "Tripledot Studios":        { platform:"greenhouse", slug:"tripledotstudios" },
  "Tripwire Interactive":     { platform:"greenhouse", slug:"tripwireinteractive" },
  "Turtle Rock Studios":      { platform:"greenhouse", slug:"turtlerockstudios" },
  "Undead Labs":              { platform:"greenhouse", slug:"undeadlabsllc" },
  "Unknown Worlds":           { platform:"greenhouse", slug:"unknownworlds" },
  "Visual Concepts":          { platform:"greenhouse", slug:"visualconcepts" },
  "Wildlife Studios":         { platform:"greenhouse", slug:"wildlifestudios" },
  "Wizards of the Coast":     { platform:"greenhouse", slug:"hasbro" },
  "Zynga":                    { platform:"greenhouse", slug:"zyngacareers" },
  // ─── Jobvite ───
  "AGS":                      { platform:"jobvite", slug:"agscareer" },
  "Amber":                    { platform:"jobvite", slug:"amberstudiocareers" },
  "Capcom":                   { platform:"jobvite", slug:"capcomusa" },
  "Probably Monsters":        { platform:"jobvite", slug:"probablymonsters" },
  // ─── Lever ───
  "Avalanche Studios":        { platform:"lever", slug:"avalanchestudios" },
  "Behaviour Interactive":    { platform:"lever", slug:"bhvr" },
  "Blackbird Interactive":    { platform:"lever", slug:"blackbirdinteractive" },
  "Demiurge Studios":         { platform:"lever", slug:"demiurgestudios" },
  "Double Down Interactive":  { platform:"lever", slug:"doubledown" },
  "Exploding Kittens":        { platform:"lever", slug:"explodingkittens" },
  "Golf Plus":                { platform:"lever", slug:"golfscopeinc" },
  "Impulse Gear":             { platform:"lever", slug:"impulsegear" },
  "Jam City":                 { platform:"lever", slug:"jamcity" },
  "Kabam":                    { platform:"lever", slug:"kabam" },
  "Larian Studios":           { platform:"lever", slug:"larian" },
  "Magnopus":                 { platform:"lever", slug:"magnopus" },
  "Playco":                   { platform:"lever", slug:"playco" },
  "Quantic Dream":            { platform:"lever", slug:"quanticdream" },
  "Ramen VR":                 { platform:"lever", slug:"ramenvr" },
  "Rovio":                    { platform:"lever", slug:"rovio-2" },
  "Skybox Labs":              { platform:"lever", slug:"skyboxlabs" },
  "Skydance":                 { platform:"lever", slug:"skydance" },
  "Theorycraft Games":        { platform:"lever", slug:"theorycraftgames" },
  // ─── Paylocity ───
  "Design Works Gaming":      { platform:"paylocity", slug:"design-works-gaming" },
  "Gunfire Games":            { platform:"paylocity", slug:"gunfire-games" },
  // ─── Recruitee ───
  "Framestore VR":            { platform:"recruitee", slug:"framestore" },
  "Rocketwerkz":              { platform:"recruitee", slug:"rocketwerkz" },
  // ─── Smart Recruiters ───
  "CD Projekt Red":           { platform:"smartrecruiters", slug:"cdprojektred" },
  "Firehose Games":           { platform:"smartrecruiters", slug:"firehosegames" },
  "Gameloft":                 { platform:"smartrecruiters", slug:"gameloft" },
  "Meta4":                    { platform:"smartrecruiters", slug:"meta4" },
  "Mighty Games Group":       { platform:"smartrecruiters", slug:"mightygames" },
  "People Can Fly":           { platform:"smartrecruiters", slug:"peoplecanfly" },
  "Tantalus Media":           { platform:"smartrecruiters", slug:"tantalus" },
  "Ubisoft":                  { platform:"smartrecruiters", slug:"ubisoft2" },
  "Unchained Entertainment":  { platform:"smartrecruiters", slug:"citystateentertainmentllc" },
  "Yacht Club Games":         { platform:"smartrecruiters", slug:"yachtclubgames" },
  // ─── Workable ───
  "Big Viking Games":         { platform:"workable", slug:"big-viking-games-3" },
  "Crazy Maple Studio":       { platform:"workable", slug:"crazymaplestudio" },
  "FunPlus":                  { platform:"workable", slug:"fun-plus" },
  "Game Sim":                 { platform:"workable", slug:"gamesim-2" },
  "Hardsuit Labs":            { platform:"workable", slug:"hardsuit-labs-1" },
  "Heavy Iron Studios":       { platform:"workable", slug:"heavy-iron-studios" },
  "High Voltage Software":    { platform:"workable", slug:"high-voltage-software" },
  "Hutch":                    { platform:"workable", slug:"hutch" },
  "Jackbox Games":            { platform:"workable", slug:"jackbox-games" },
  "KingsIsle Entertainment":  { platform:"workable", slug:"kingsisle-entertainment-inc" },
  "KOMODO Corporation":       { platform:"workable", slug:"komodo-co-dot-ltd" },
  "Mad Mushroom":             { platform:"workable", slug:"otk-media" },
  "Moonbug":                  { platform:"workable", slug:"moonbugentertainment" },
  "N3twork Studios":          { platform:"workable", slug:"n3twork-studios" },
  "Nexus Studios":            { platform:"workable", slug:"nexusstudios" },
  "Owlchemy Labs":            { platform:"workable", slug:"owlchemy-labs" },
  "PikPok":                   { platform:"workable", slug:"pikpok" },
  "Pixelberry Studios":       { platform:"workable", slug:"pixelberry-studios" },
  "Secret 6":                 { platform:"workable", slug:"secret-6" },
  "Smoking Gun Interactive":  { platform:"workable", slug:"smoking-gun-interactive-1" },
  "Soulbound Studios":        { platform:"workable", slug:"soulbound" },
  "Sperasoft":                { platform:"workable", slug:"sperasoft" },
  "Square Enix":              { platform:"workable", slug:"square-enix-america" },
  "Velan Studios":            { platform:"workable", slug:"velanstudios" },
  "Vertigo Games":            { platform:"workable", slug:"vertigogames" },
};